### get all
GET http://localhost:3000/api/organization HTTP/1.1
content-type: application/json

### get one
GET http://localhost:3000/api/organization/786133502888280066 HTTP/1.1
content-type: application/json

### insert one
POST http://localhost:3000/api/organization HTTP/1.1
content-type: application/json

{
    "name": "Organization 001",
    "status": 1
}

### delete all
DELETE  http://localhost:3000/api/organization HTTP/1.1
content-type: application/json