### get all
GET http://localhost:3000/organization HTTP/1.1
content-type: application/json

### get one
GET http://localhost:3000/organization/1 HTTP/1.1
content-type: application/json

### insert one
POST http://localhost:3000/organization HTTP/1.1
content-type: application/json

{
    "name": "Organization 001",
    "status": 1
}