
### get all 
GET http://localhost:3000/repository HTTP/1.1
content-type: application/json

### get one
GET http://localhost:3000/repository/1 HTTP/1.1
content-type: application/json

### insert one
POST http://localhost:3000/repository HTTP/1.1
content-type: application/json

{
    "id_tribe": 1,
    "name": "Repository 002",
    "state": "1",
    "status": 1
}